# TASK-1

In [4]:
import pandas as pd
data=pd.read_csv('winequality-red.csv')
print(data.head(20))

    fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0             7.4             0.700         0.00             1.9      0.076
1             7.8             0.880         0.00             2.6      0.098
2             7.8             0.760         0.04             2.3      0.092
3            11.2             0.280         0.56             1.9      0.075
4             7.4             0.700         0.00             1.9      0.076
5             7.4             0.660         0.00             1.8      0.075
6             7.9             0.600         0.06             1.6      0.069
7             7.3             0.650         0.00             1.2      0.065
8             7.8             0.580         0.02             2.0      0.073
9             7.5             0.500         0.36             6.1      0.071
10            6.7             0.580         0.08             1.8      0.097
11            7.5             0.500         0.36             6.1      0.071
12            5.6             0.615         0.00             1.6      0.089
13            7.8             0.610         0.29             1.6      0.114
14            8.9             0.620         0.18             3.8      0.176
15            8.9             0.620         0.19             3.9      0.170
16            8.5             0.280         0.56             1.8      0.092
17            8.1             0.560         0.28             1.7      0.368
18            7.4             0.590         0.08             4.4      0.086
19            7.9             0.320         0.51             1.8      0.341

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                  11.0                  34.0   0.9978  3.51       0.56
1                  25.0                  67.0   0.9968  3.20       0.68
2                  15.0                  54.0   0.9970  3.26       0.65
3                  17.0                  60.0   0.9980  3.16       0.58
4                  11.0                  34.0   0.9978  3.51       0.56
5                  13.0                  40.0   0.9978  3.51       0.56
6                  15.0                  59.0   0.9964  3.30       0.46
7                  15.0                  21.0   0.9946  3.39       0.47
8                   9.0                  18.0   0.9968  3.36       0.57
9                  17.0                 102.0   0.9978  3.35       0.80
10                 15.0                  65.0   0.9959  3.28       0.54
11                 17.0                 102.0   0.9978  3.35       0.80
12                 16.0                  59.0   0.9943  3.58       0.52
13                  9.0                  29.0   0.9974  3.26       1.56
14                 52.0                 145.0   0.9986  3.16       0.88
15                 51.0                 148.0   0.9986  3.17       0.93
16                 35.0                 103.0   0.9969  3.30       0.75
17                 16.0                  56.0   0.9968  3.11       1.28
18                  6.0                  29.0   0.9974  3.38       0.50
19                 17.0                  56.0   0.9969  3.04       1.08

    alcohol  quality
0       9.4        5
1       9.8        5
2       9.8        5
3       9.8        6
4       9.4        5
5       9.4        5
6       9.4        5
7      10.0        7
8       9.5        7
9      10.5        5
10      9.2        5
11     10.5        5
12      9.9        5
13      9.1        5
14      9.2        5
15      9.2        5
16     10.5        7
17      9.3        5
18      9.0        4
19      9.2        6

# TASK-2

In [5]:
data.loc[(data.density < 1) | (data.pH > 3)]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

# TASK-3

In [10]:
import pandas as pd

data['fixed acidity'].describe()

count    1599.000000
mean        8.319637
std         1.741096
min         4.600000
25%         7.100000
50%         7.900000
75%         9.200000
max        15.900000
Name: fixed acidity, dtype: float64

# TASK-4

In [14]:
data.sort_values(by='free sulfur dioxide')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
535,9.1,0.220,0.24,2.1,0.078,1.0,28.0,0.99900,3.41,0.87,10.3,6
773,7.9,0.400,0.29,1.8,0.157,1.0,44.0,0.99730,3.30,0.92,9.5,6
530,9.1,0.220,0.24,2.1,0.078,1.0,28.0,0.99900,3.41,0.87,10.3,6
774,7.9,0.400,0.30,1.8,0.157,2.0,45.0,0.99727,3.31,0.91,9.5,6
1277,7.0,0.690,0.00,1.9,0.114,3.0,10.0,0.99636,3.35,0.60,9.7,6
...,...,...,...,...,...,...,...,...,...,...,...,...
1131,5.9,0.190,0.21,1.7,0.045,57.0,135.0,0.99341,3.32,0.44,9.5,5
1558,6.9,0.630,0.33,6.7,0.235,66.0,115.0,0.99787,3.22,0.56,9.5,5
396,6.6,0.735,0.02,7.9,0.122,68.0,124.0,0.99940,3.47,0.53,9.9,5
400,6.6,0.735,0.02,7.9,0.122,68.0,124.0,0.99940,3.47,0.53,9.9,5
1244,5.9,0.290,0.25,13.4,0.067,72.0,160.0,0.99721,3.33,0.54,10.3,6

# TASK-5

In [15]:
data.quality.replace(5,10)

0       10
1       10
2       10
3        6
4       10
        ..
1594    10
1595     6
1596     6
1597    10
1598     6
Name: quality, Length: 1599, dtype: int64

# TASK-6

In [21]:
data.rename(columns={'free sulfur dioxide': 'FSD','total sulfur dioxide': 'TSD'},inplace = True)
data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,FSD,TSD,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

# TASK-7

Pandas is a really good library which can be used for data manipulation and data visuzlization. 

Pandas provide a really good and detailed data representation.
Pandas has a really good set of commands and features where it can be used for analyzing data easier.
Pandas can handle large det of data.
Pandas enables us to edit, and customize the data set according to our use.